### ISSUE TITLE
Finalizing features/pages

### ISSUE THREAD

**Issue by shreyaparadkar** [AzTechs-Team/cluster#3]

**Comment by shreyaparadkar** [comment]
- Product landing page (without login)
  - Hero container with a call to action btn
  - Features
  - How to use cluster
  - Explore - communities & events
  - Searchbar 
  - Login/Register
  - Register your college
  
- Pricing policy (without login)

- Event details (without login)

- Community details (without login) 
  - Subscribe to the community 
 
- University details page (without login + Redirected here after login)
  - Communities
  - Events
  - Past events

- Student view 
  - Feed - upcoming events, calendar view, new communities, events from subscribed communities
  - Profile - registered events, personal details, subscribed communities, badges received
  - University explore page (same as uni details page)
  - Global explore page 
  - Logout

- Uni-Community view
  - CRUD events 
  - Digital badges
  - Analytics

- University view
  - CRUD communities
  - CRUD events
  - Billing and monitoring
  - Help bot
  - Analytics

- Community view (low priority)
  - CRUD events

**Comment by shreyaparadkar** [comment]
Gamify the experience
- Digital badges
- Subscribe to x communities
- Attend x online events
- Attend x offline events
- Get custom swags in return 
- Attend cultural + tech events
- Different levels

**Comment by nimit2801** [comment]
Sysadmin Page
- Description: This page helps us to get analytics and managing university profiles
